services:
  app:
    build:
      context: .
      dockerfile: infrastructure/docker/app/Dockerfile
      args:
        - USER_NAME=${USER_NAME:-app}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    ports:
      - 3000:3000
    volumes:
      - ./src:/app
    environment:
      - USER_NAME=${USER_NAME}
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    working_dir: /app
    entrypoint: ["/bin/bash"]
    command: ["-i"]
